name: Python tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fortify repo
      uses: actions/checkout@v3
      with:
        path: fortify

    - name: Checkout test suite repo
      uses: actions/checkout@v3
      with:
        repository: louoberto/test
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r fortify/requirements.txt

    - name: Run tests and compare results
      run: |
        mkdir -p reports
        for file in test/testfile_??.f*; do
          base=$(basename "$file")
          keyfile="test/keyfile_${base#testfile_}"
          if [[ -f "$keyfile" ]]; then
            echo "Running: python fortify/source/main.py $file"
            python fortify/source/main.py "$file"
            echo "Comparing $file with $keyfile"
            diff "$file" "$keyfile" > reports/diff_${base#testfile_}.log || echo "Diff found for $file" >> reports/errors.log
          else
            echo "Keyfile $keyfile not found for $file" >> reports/errors.log
          fi
        done
    - name: Show error log if differences found
      if: failure()
      run: cat reports/errors.log
